### ISSUE TITLE
An issue about re-initialize CUDA in forked subprocess

### ISSUE THREAD

**Issue by healenrens** [justheuristic/prefetch_generator#9]
hello,
Your program is very useful,thank you!
but when I need to use gpus to pre-processing my data like do some processing in function __getitem__  and set the num_works!=0,there will be an error:
"RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method"
I have tried to change your code but maybe I am not well in understanding it,I can not fix it.
so would you like to add a support of that?
thanks!

**Comment by justheuristic** [comment]
Hi, @healenrens !

Unfortunately, this behavior is expected: torch cannot initialize cuda twice. Furthermore, it is not specific to prefetch_generator: this error will be triggered by any code that initializes cuda, then spawns a background process and initializes cuda again.

To the best of my knowledge, the only way to bypass that is to ensure that all processes are forked before cuda is initialized, for example:
- master process starts, does **not** initialize CUDA yet
- master process creates multiprocessing.Queue for receiving results
- master process creates a forks for preprocessing
- fork initializes CUDA, begins preprocessing minibatches and puts them into multiprocessing.Queue
- master initializes CUDA, receives minibatches from multiprocessing.Queue and runs training

This behavior is not possible with prefetch_generator, so you will have to write custom code or use another library.

**Comment by healenrens** [comment]
Thanks for your reply of my question.I have learned about it and I will try to write custom code.
